In [150]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score

In [119]:
train = pd.read_csv(r'C:\Users\91938\Desktop\Machine learning\train.csv')

In [120]:
test = pd.read_csv(r'C:\Users\91938\Desktop\Machine learning\test.csv')

In [121]:
sample = pd.read_csv(r'C:\Users\91938\Desktop\Machine learning\gender_submission.csv')

In [122]:
train.shape, test.shape, sample.shape

((891, 12), (418, 11), (418, 2))

In [123]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [124]:
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [125]:
sample.head()

PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1

In [126]:
data = pd.concat([train, test])

In [127]:
data.head()

PassengerId  Survived  Pclass  \
0            1       0.0       3   
1            2       1.0       1   
2            3       1.0       3   
3            4       1.0       1   
4            5       0.0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [128]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1309 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  1309 non-null   int64  
 1   Survived     891 non-null    float64
 2   Pclass       1309 non-null   int64  
 3   Name         1309 non-null   object 
 4   Sex          1309 non-null   object 
 5   Age          1046 non-null   float64
 6   SibSp        1309 non-null   int64  
 7   Parch        1309 non-null   int64  
 8   Ticket       1309 non-null   object 
 9   Fare         1308 non-null   float64
 10  Cabin        295 non-null    object 
 11  Embarked     1307 non-null   object 
dtypes: float64(3), int64(4), object(5)
memory usage: 132.9+ KB


In [129]:
data['PassengerId'].value_counts(dropna = False)

1       1
861     1
879     1
878     1
877     1
       ..
436     1
435     1
434     1
433     1
1309    1
Name: PassengerId, Length: 1309, dtype: int64

In [130]:
data['Survived'].value_counts(dropna = False)

0.0    549
NaN    418
1.0    342
Name: Survived, dtype: int64

In [131]:
data.isna().sum()

PassengerId       0
Survived        418
Pclass            0
Name              0
Sex               0
Age             263
SibSp             0
Parch             0
Ticket            0
Fare              1
Cabin          1014
Embarked          2
dtype: int64

In [132]:
data['Age'].fillna('0', inplace = True)

In [133]:
data['Fare'].fillna('0', inplace = True)

In [134]:
data['Cabin'].fillna('unknown', inplace = True)

In [135]:
one_hot = pd.get_dummies(data, columns = ['Pclass', 'Sex', 'SibSp', 'Parch', 'Embarked'])

In [136]:
one_hot.head()

PassengerId  Survived                                               Name  \
0            1       0.0                            Braund, Mr. Owen Harris   
1            2       1.0  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2            3       1.0                             Heikkinen, Miss. Laina   
3            4       1.0       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4            5       0.0                           Allen, Mr. William Henry   

    Age            Ticket     Fare    Cabin  Pclass_1  Pclass_2  Pclass_3  \
0  22.0         A/5 21171     7.25  unknown         0         0         1   
1  38.0          PC 17599  71.2833      C85         1         0         0   
2  26.0  STON/O2. 3101282    7.925  unknown         0         0         1   
3  35.0            113803     53.1     C123         1         0         0   
4  35.0            373450     8.05  unknown         0         0         1   

   ...  Parch_1  Parch_2  Parch_3  Parch_4  Parch_5  Parch_6  Parch_9  \
0  ...        0        0        0        0        0        0        0   
1  ...        0        0        0        0        0        0        0   
2  ...        0        0        0        0        0        0        0   
3  ...        0        0        0        0        0        0        0   
4  ...        0        0        0        0        0        0        0   

   Embarked_C  Embarked_Q  Embarked_S  
0           0           0           1  
1           1           0           0  
2           0           0           1  
3           0           0           1  
4           0           0           1  

[5 rows x 30 columns]

In [137]:
one_hot.drop(columns = ['Name', 'Ticket', 'Fare', 'Cabin'], inplace = True)

In [138]:
one_hot = one_hot.reset_index(drop = True)

In [139]:
data_preprocessed = pd.DataFrame(one_hot)

In [140]:
data_preprocessed.head(10)

PassengerId  Survived   Age  Pclass_1  Pclass_2  Pclass_3  Sex_female  \
0            1       0.0  22.0         0         0         1           0   
1            2       1.0  38.0         1         0         0           1   
2            3       1.0  26.0         0         0         1           1   
3            4       1.0  35.0         1         0         0           1   
4            5       0.0  35.0         0         0         1           0   
5            6       0.0     0         0         0         1           0   
6            7       0.0  54.0         1         0         0           0   
7            8       0.0   2.0         0         0         1           0   
8            9       1.0  27.0         0         0         1           1   
9           10       1.0  14.0         0         1         0           1   

   Sex_male  SibSp_0  SibSp_1  ...  Parch_1  Parch_2  Parch_3  Parch_4  \
0         1        0        1  ...        0        0        0        0   
1         0        0        1  ...        0        0        0        0   
2         0        1        0  ...        0        0        0        0   
3         0        0        1  ...        0        0        0        0   
4         1        1        0  ...        0        0        0        0   
5         1        1        0  ...        0        0        0        0   
6         1        1        0  ...        0        0        0        0   
7         1        0        0  ...        1        0        0        0   
8         0        1        0  ...        0        1        0        0   
9         0        0        1  ...        0        0        0        0   

   Parch_5  Parch_6  Parch_9  Embarked_C  Embarked_Q  Embarked_S  
0        0        0        0           0           0           1  
1        0        0        0           1           0           0  
2        0        0        0           0           0           1  
3        0        0        0           0           0           1  
4        0        0        0           0           0           1  
5        0        0        0           0           1           0  
6        0        0        0           0           0           1  
7        0        0        0           0           0           1  
8        0        0        0           0           0           1  
9        0        0        0           1           0           0  

[10 rows x 26 columns]

In [141]:
data_preprocessed['Age'].unique()

array([22.0, 38.0, 26.0, 35.0, '0', 54.0, 2.0, 27.0, 14.0, 4.0, 58.0,
       20.0, 39.0, 55.0, 31.0, 34.0, 15.0, 28.0, 8.0, 19.0, 40.0, 66.0,
       42.0, 21.0, 18.0, 3.0, 7.0, 49.0, 29.0, 65.0, 28.5, 5.0, 11.0,
       45.0, 17.0, 32.0, 16.0, 25.0, 0.83, 30.0, 33.0, 23.0, 24.0, 46.0,
       59.0, 71.0, 37.0, 47.0, 14.5, 70.5, 32.5, 12.0, 9.0, 36.5, 51.0,
       55.5, 40.5, 44.0, 1.0, 61.0, 56.0, 50.0, 36.0, 45.5, 20.5, 62.0,
       41.0, 52.0, 63.0, 23.5, 0.92, 43.0, 60.0, 10.0, 64.0, 13.0, 48.0,
       0.75, 53.0, 57.0, 80.0, 70.0, 24.5, 6.0, 0.67, 30.5, 0.42, 34.5,
       74.0, 22.5, 18.5, 67.0, 76.0, 26.5, 60.5, 11.5, 0.33, 0.17, 38.5],
      dtype=object)

In [142]:
preprocessed_train = data_preprocessed[data_preprocessed['Survived'].notna()]
preprocessed_test = data_preprocessed[data_preprocessed['Survived'].isna()]

In [143]:
x = preprocessed_train.drop(columns = ['PassengerId', 'Survived'])
y = preprocessed_train['Survived']

### Train_test_split

In [144]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 40)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((712, 24), (179, 24), (712,), (179,))

### Fitting the model

In [145]:
model = LogisticRegression()

In [146]:
model.fit(x_train, y_train)

C:\Users\91938\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [147]:
model.coef_

array([[-0.01395769,  0.84071681,  0.08387866, -1.01723088,  1.19060046,
        -1.28323587,  0.52078086,  0.75891605,  0.64657084, -0.77630262,
        -0.348511  , -0.11036354, -0.783726  ,  0.15645204,  0.46228697,
         0.36388626,  0.1610223 , -0.71210583, -0.52417715,  0.        ,
         0.        ,  0.15452461, -0.00745925, -0.32449246]])

In [148]:
model.intercept_

array([-0.09159567])

### Predicting train set

In [149]:
y_pred_train = model.predict(x_train)

In [151]:
print('accuracy_score:',accuracy_score(y_train, y_pred_train))
print('f1_score:', f1_score(y_train, y_pred_train))
print('confusion_matrix:\n', confusion_matrix(y_train, y_pred_train))

accuracy_score: 0.7991573033707865
f1_score: 0.7134268537074148
confusion_matrix:
 [[391  55]
 [ 88 178]]


### Predicting test set

In [152]:
y_pred_test = model.predict(x_test)

In [154]:
print('accuracy_score:',accuracy_score(y_test, y_pred_test))
print('f1_score:', f1_score(y_test, y_pred_test))
print('confusion_matrix:\n', confusion_matrix(y_test, y_pred_test))

accuracy_score: 0.8212290502793296
f1_score: 0.7837837837837838
confusion_matrix:
 [[89 14]
 [18 58]]


In [155]:
preprocessed_x_test = preprocessed_test.drop(columns=['PassengerId','Survived'])
y_prediction = model.predict(preprocessed_x_test)

In [156]:
sample['Survived'] = y_prediction
sample.to_csv('submission_titanic_disaster_prediction.csv',index=False)